export const PERMISSIONS = {
  CUSTOMER: {
    CREATE: 'CUSTOMER_CREATE',
    READ: 'CUSTOMER_READ',
    UPDATE: 'CUSTOMER_UPDATE',
    DELETE: 'CUSTOMER_DELETE'
  },
  PROJECT: {
    CREATE: 'PROJECT_CREATE',
    READ: 'PROJECT_READ',
    UPDATE: 'PROJECT_UPDATE',
    DELETE: 'PROJECT_DELETE'
  },
  TIMESHEET: {
    CREATE: 'TIMESHEET_CREATE',
    READ: 'TIMESHEET_READ',
    UPDATE: 'TIMESHEET_UPDATE',
    DELETE: 'TIMESHEET_DELETE',
    SUBMIT: 'TIMESHEET_SUBMIT',
    REVIEW: 'TIMESHEET_REVIEW'
  },
  };
